// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkEiDw14GzTnEXYjnh9ZTb5qZqR7Nq19M',
    appId: '1:656631009880:web:fd33012a2dfab65532b02d',
    messagingSenderId: '656631009880',
    projectId: 'jackienotes',
    authDomain: 'jackienotes.firebaseapp.com',
    storageBucket: 'jackienotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-WQdTTuM_cIol9LNewJ4MGKybQEq0RLA',
    appId: '1:656631009880:android:94d1a484c10f4aa732b02d',
    messagingSenderId: '656631009880',
    projectId: 'jackienotes',
    storageBucket: 'jackienotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuGRe8KjrzrCU1Dju3KU-D2d7ZRCWvxfs',
    appId: '1:656631009880:ios:01812dd340c404b232b02d',
    messagingSenderId: '656631009880',
    projectId: 'jackienotes',
    storageBucket: 'jackienotes.appspot.com',
    iosBundleId: 'com.example.basicRegistrationForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuGRe8KjrzrCU1Dju3KU-D2d7ZRCWvxfs',
    appId: '1:656631009880:ios:51e526b67b06768a32b02d',
    messagingSenderId: '656631009880',
    projectId: 'jackienotes',
    storageBucket: 'jackienotes.appspot.com',
    iosBundleId: 'com.example.basicRegistrationForm.RunnerTests',
  );
}
